### ISSUE TITLE
Slow viewer with many, big points close to each other.

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2101]
## 🐛 Bug

If a points layer includes a lot of points whose size is big relatively to their relative distance, the viewer becomes slow and chockes up the system resources. ~This does not happen in 0.4.2~.

## To Reproduce

```python
import napari
import numpy as np
v = napari.Viewer(ndisplay=3)
# lots of overlapping points with coordinates between 0 and 1, and default size of 10
v.add_points(np.random.rand(10000, 3))
```

however, this works fine:
```python
import napari
import numpy as np
v = napari.Viewer(ndisplay=3)
# size = 0.01
v.add_points(np.random.rand(10000, 3), size=0.01)
```

## Expected behavior

Size does not matter :)

## Environment
```yaml
napari: 0.4.2
Platform: Linux-5.10.6-arch1-1-x86_64-with-glibc2.32
Python: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2020.12.0
VisPy: 0.6.6

GL version: 4.6.0 NVIDIA 460.32.03
MAX_TEXTURE_SIZE: 16384

Plugins:
- mrcfile-reader: 0.1.2
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```
