### ISSUE TITLE
Manually closing the qt viewer causes qt RuntimeErrors when re-adding layers

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2110]
## 🐛 Bug

If the viewer is closed manually from the os side (but not when using `viewer.close()`), layers that were present in the viewer will be "tainted", and cause a few runtime errors if later re-added to another viewer.

## To Reproduce
Normal behaviour:
```python
pl = napari.layers.Points()

v = napari.Viewer()
v.layers.append(pl)
# close it programmatically
v.close()
# make a new viewer and append the layer
v = napari.Viewer()
v.layers.append(pl)
# click anywhere on the layerlist widget: nothing bad happens (foreshadowing...).
```
If closed manually, bugs arise:
```python
pl = napari.layers.Points()

v = napari.Viewer()
v.layers.append(pl)
# close it manually...
# then create a new one and append the layer
v = napari.Viewer()
v.layers.append(pl)
```
After the last step, one of two things will happen:
- if before closing the viewer you *deselected* the layer, this error is raised:
```python
.../lib/python3.9/site-packages/napari/_qt/qt_main_window.py in _status_changed(self, event)
    867             The napari event that triggered this method.
    868         """
--> 869         self._status_bar.showMessage(event.value)
    870 
    871     def _title_changed(self, event):

RuntimeError: wrapped C/C++ object of type QStatusBar has been deleted
```
- if you left the layer *selected*, nothing happens until you click anywhere on the layerlist widget, which fires the same error. This however appears in a weird way in ipython, a non-colored, "streaming" kind of way that I don't quite understand.

## Environment
```yaml
napari: 0.4.3rc2
Platform: Linux-5.10.6-arch1-1-x86_64-with-glibc2.32
Python: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2.30.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.32.03
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen #1: resolution 1920x1080, scale 1.0

Plugins:
- napari_plugin_engine: 0.1.9
- svg: 0.1.4
```
