### ISSUE TITLE
Points very close to each other overlap wrongly in 3d

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2138]
## 🐛 Bug

I found another issue with visualisation of highly packed points (see #2101). If coordinate differences are small (e.g: a cloud of points between 0 and 1), napari often messes up the foreground/background ordering of the points.

## To Reproduce
```python
v = napari.Viewer(ndisplay=3)
p = np.random.rand(100, 3) * (0.1, 0.01, 0.1)
v.add_points(p, size=0.01)
```
Then move the view around. Chances are, things are looking trippy!

## Expected behavior

Points are covering other points based on their distance from the camera.

## Environment

```yaml
napari: 0.4.3
Platform: Linux-5.10.7-arch1-1-x86_64-with-glibc2.32
Python: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.32.03
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen #1: resolution 1920x1080, scale 1.0
- screen #2: resolution 1920x1200, scale 1.0

Plugins:
- mrcfile-reader: 0.1.2
- napari_plugin_engine: 0.1.9
- ndtiffs: 0.1.1
- svg: 0.1.4
```
