### ISSUE TITLE
A few image layer scale issues

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2348]
## 🐛 Bug

I've been trying out some layer scaling. I'm putting this separately from #2347 , but it's part of the same "family" of issues, that probably stem from a combination of assumptions about the `scale` argument's nature and inconsistencies between attribute setting on layer object and calling `viewer.add_*`.

Issues I found:
- image scaling does not accept scalars.
- passing a scale vector of length equal or "slighly longer" than the EXTENT of the last dimension of the image raises an error.

## To Reproduce

 The two following snippets raise the same error, despite the second being "correct" as far as I can tell, since it tries to rescale a 3D image with a length 3 vector:
```python
viewer.add_image(np.ones((3, 3)), scale=np.ones(3,))    # fails (len3 vector with 2D image)
viewer.add_image(np.ones((3, 3, 3)), scale=np.ones(3,))    # fails with the same error!
```
```python
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)
```
Strangely, this seems connected to the extent of the last dimension of the image. Simply changing it from 3 to 5 (but not 4!) will fix it:
```python
viewer.add_image(np.ones((3, 3, 4)), scale=np.ones(3,))    # fails again
viewer.add_image(np.ones((3, 3, 5)), scale=np.ones(3,))    # works!
```
Even more strangely, this fails with a *different* error:
```python
viewer.add_image(np.ones((3, 3, 3, 4)), scale=np.ones(4,)
```
```python
ValueError: could not broadcast input array from shape (4,4) into shape (3,3)
```

## Environment
```yaml
napari: 0.4.6
Platform: Linux-5.11.2-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.1
SciPy: 1.6.1
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.56
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- ndtiffs: 0.1.1
- svg: 0.1.4
```
