### ISSUE TITLE
Xarray and vectors

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2384]
## 🐛 Bug

While adding points and images from an xarray works fine, adding **vectors** from an xarray fails with a dimensionality error.

 *I'm flagging this as bug, though it's also somewhat of a feature request, since xarray is not yet officially supported.* Likely related to #2374.

## To Reproduce

```python
import napari
import numpy as np
import xarray as xr

viewer = napari.Viewer()

vect = np.random.rand(5, 2, 2)
viewer.add_vectors(vect)  # works fine

vect_xr = xr.DataArray(vect)
viewer.add_vectors(vect_xr)  # fails
```
```python
/usr/lib/python3.9/site-packages/xarray/core/variable.py in _parse_dimensions(self, dims)
    559         dims = tuple(dims)
    560         if len(dims) != self.ndim:
--> 561             raise ValueError(
    562                 "dimensions %s must have the same length as the "
    563                 "number of data dimensions, ndim=%s" % (dims, self.ndim)

ValueError: dimensions ('dim_0', 'dim_1', 'dim_2') must have the same length as the number of data dimensions, ndim=2
```

## Environment

```yaml
napari: 0.4.6
Platform: Linux-5.11.2-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.1
SciPy: 1.6.1
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.56
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- ndtiffs: 0.1.1
- svg: 0.1.4
```
