### ISSUE TITLE
Wrong "depth relationship" of 3D isosurfaces

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2418]
## 🐛 Bug

Image layers in 3D are drawn with a simple bottom-to-top order, which is not what one would expect from isosurfaces.
For example:
![](https://i.ibb.co/1JDCN9M/Peek-2021-03-15-14-43.gif)

(I think I remember seeing similar behaviour with other visualizations, though I can't recall exactly what it was. I couldn't find an issue about this, but maybe I'm looking for the wrong keywords.)

## To Reproduce

A simple example:
```python
v = napari.Viewer(ndisplay=3)
v.add_image(np.arange(1000).reshape(10, 10, 10), iso_threshold=0.7, rendering='iso')
v.add_image(np.arange(1000, 0, -1).reshape(10, 10, 10), iso_threshold=0.7, rendering='iso')
```
Then move it around.

## Expected behavior

The "depth relationship" of the isosurfaces should be determined based on the physical distance from the camera, rather than simply be based on layer order. I'm not sure if layer order should have any meaning here, of if I'm missing some important point.

## Environment

```yaml
napari: 0.4.6
Platform: Linux-5.11.4-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.1
SciPy: 1.6.1
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.56
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- ndtiffs: 0.1.1
- svg: 0.1.4
```
