### ISSUE TITLE
`schema_version` should be typed and preferably serialized to string

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2526]
Everything in our settings models should have type annotations.  
Currently, all of the `schema_version` fields are untyped tuples of ints:
```python
class AppearanceSettings(BaseNapariSettings):
    schema_version = (0, 1, 0)
```
this means they serialize to our settings like this:
```yaml
appearance:
  schema_version:
  - 0
  - 1
  - 0
  theme: dark
```

which is a little hard to visually parse.  Since it's used in every submodel, it would be nice to have a `SchemaVersion` field that handles ser/des so that can be:
```yaml
appearance:
  schema_version: 0.1.0
  theme: dark
```
