### ISSUE TITLE
Transparency of points in 3D is broken

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2665]
## 🐛 Bug

When the `face_color` of points is transparent, 3D visualization of said points is a bit of a mess, with points switching from black to invisible, depending on camera rotation. There's also some inconsistency in how sometimes points have a thick black border to distinguish them from the ones behind, and sometimes not.

Might have something to deal with order of painting in vispy, like in #2138 and #2418.

## To Reproduce

**Edit:** Updated on 9/8/2025 by @jni to reflect recent API changes.

```python
import numpy as np
import napari

data = np.random.rand(200, 3) * 200
vis = np.random.choice([True, False], 200)
categorical_cmap = {True: [1, 1, 1, 1], False: [0, 0, 0, 0]}
face_color = {
    'colors': 'vis',
    'categorical_colormap': categorical_cmap,
    'mode': 'cycle'
}

v = napari.Viewer(ndisplay=3)
l = v.add_points(data, properties={'vis': vis}, face_color=face_color, border_color=[0, 0, 0, 0])

napari.run()
```

![napari_anim](https://user-images.githubusercontent.com/23482191/117267476-99760080-ae56-11eb-96fb-6c234869d02c.gif)

## Expected behavior

Points should be *really* invisible when alpha is set to zero.

## Environment

```yaml
napari: 0.4.7
Platform: Linux-5.11.16-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.4 (default, Apr 20 2021, 15:51:38) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.3
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 465.27
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.1
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- ndtiffs: 0.1.1
- svg: 0.1.4
```
