### ISSUE TITLE
Selecting points fails if a property value has dtype `object`

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2756]
## 🐛 Bug

Selecting points will raise an error if the points layer has a property aarray with dtype `object`. This leaves in an inconsistent state where `Points.selected_data` is updated, but `Points.current_property` is broken.

## To Reproduce
```python
#!/usr/bin/env python3

import napari
import numpy as np

pt = np.random.rand(100, 2)
props = {'prop': np.zeros(100, dtype=object)}

v = napari.Viewer()
pl = v.add_points(pt, properties=props)

sele = np.arange(50)

pl.selected_data = sele
```
this raises this error:
```python
~/.local/lib/python3.9/site-packages/napari/layers/points/points.py in selected_data(self, selected_data)
   1032                 self.current_size = size
   1033 
-> 1034         properties = {
   1035             k: np.unique(v[index], axis=0) for k, v in self.properties.items()
   1036         }

~/.local/lib/python3.9/site-packages/napari/layers/points/points.py in <dictcomp>(.0)
   1033 
   1034         properties = {
-> 1035             k: np.unique(v[index], axis=0) for k, v in self.properties.items()
   1036         }
   1037         n_unique_properties = np.array([len(v) for v in properties.values()])

<__array_function__ internals> in unique(*args, **kwargs)

/usr/lib/python3.9/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts, axis)
    293         # There's no good way to do this for object arrays, etc...
    294         msg = 'The axis argument to unique is not supported for dtype {dt}'
--> 295         raise TypeError(msg.format(dt=ar.dtype)) from e
    296 
    297     def reshape_uniq(uniq):

TypeError: The axis argument to unique is not supported for dtype object
```

At this point, `pl.selected_data` is right, but `pl.current_properties` is not.

## Expected behavior

I would expect either to be disallowed to set properties with dtype object (in case this can't be solved), or that this should work.

## Environment

```yaml
napari: 0.4.8
Platform: Linux-5.12.5-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.5 (default, May 12 2021, 17:14:51) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.3
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 465.31
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.1
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-properties-plotter: 0.1.dev2+g2734460.d20210520
- ndtiffs: 0.1.1
- scikit-image: 0.4.8
- svg: 0.1.4
```
