### ISSUE TITLE
Surface layer error with over 1e7 vertices

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2811]
## 🐛 Bug

When a surface layer is created with more than `1e7` vertices, an unexpected error shows up. I think napari is trying to do some magic with setting contrast limits, but fails before getting to it due to wrong indexing.

## To Reproduce

```python
import numpy as np
from napari.layers import Surface
Surface((np.zeros((100000000, 3)), np.zeros((1, 3), dtype=int)))
```
Error raised:
```
~/.local/lib/python3.9/site-packages/napari/layers/surface/surface.py in __init__(self, data, colormap, contrast_limits, gamma, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible)
    168         self._gamma = gamma
    169         if contrast_limits is None:
--> 170             self._contrast_limits_range = calc_data_range(self._vertex_values)
    171         else:
    172             self._contrast_limits_range = contrast_limits

~/.local/lib/python3.9/site-packages/napari/layers/utils/layer_utils.py in calc_data_range(data, rgb)
     38         if (
     39             np.prod(data.shape[-offset:]) > 1e7
---> 40             and data.shape[-offset] > 64
     41             and data.shape[-offset + 1] > 64
     42         ):

IndexError: tuple index out of range
```

## Expected behavior

I'm not sure if this is supposed to fail and the error is just hard to interpret, or if it's unwanted behaviour.

## Environment

```yaml
napari: 0.4.8
Platform: Linux-5.12.8-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 465.31
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-properties-plotter: 0.1.dev2+g2734460.d20210520
- ndtiffs: 0.1.1
- scikit-image: 0.4.8
- svg: 0.1.5
```
