### ISSUE TITLE
Using arrow keys to switch selected layer skips one layer

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2829]
## 🐛 Bug

If a layer is selected and you press the up/down arrow keys, instead of switching to the next/previous layer, it will skip over one layer.

## To Reproduce

Open napari, create create a bunch of layers, select one of them and press `up` or `down`.

## Expected behavior

The adjacent layer should be selected.

## Environment
```yaml
napari: 0.4.9rc0
Platform: Linux-5.12.8-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 465.31
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-properties-plotter: 0.1.dev2+g2734460.d20210520
- ndtiffs: 0.1.1
- scikit-image: 0.4.8
- svg: 0.1.5
```
