### ISSUE TITLE
Point sizes not always absolute

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#2894]
## 🐛 Bug

Point sizes are absolute relative to image pixels when `Viewer.camera.zoom` is less than the size of the points .
`size=4` gives points with a diameter of 4 image pixels but when zooming in beyond `zoom=4` this is no longer true, they become smaller than 4 image pixels)

![image](https://user-images.githubusercontent.com/7307488/122306295-1689a080-cf00-11eb-8a0d-5c1fcdc4b03c.png)
In the image above, at zoom 2.4 and zoom 4 the points are exactly 4 image pixels. At zoom 10 they are significantly smaller

## To Reproduce
```python
import napari
import numpy as np

viewer = napari.Viewer()

image = np.zeros((100, 100))
image[::2, ::2] = 1

viewer.add_image(image)

x = np.linspace(4, 94, 10, endpoint=True)
yy, xx = np.meshgrid(x, x)
yx = np.vstack((yy.flatten(), xx.flatten())).transpose()

viewer.add_points(yx, size=4, face_color='cornflowerblue')
```

1. run above example
2. play with zoom
3. note how point diameters are constant 4 image pixels (seen on grid below) at `Viewer.camera.zoom` < 4
4. note how point diameters become smaller than 4 image pixels at `Viewer.camera.zoom` > 4

cc @brisvag

**Comment by brisvag** [comment]
As we already discovered, I cannot reproduce on my work computer. Apparently, I also cannot reproduce on my laptop. This is zoom 32:

![image](https://user-images.githubusercontent.com/23482191/122346630-78222d00-cf49-11eb-8ca2-775fe647eb06.png)

```yaml
napari: 0.4.9
Platform: Linux-5.12.9-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.1
SciPy: 1.6.3
Dask: 2.30.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 465.31
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-properties-plotter: 0.1.0
- scikit-image: 0.4.8
- svg: 0.1.5
```

**Comment by alisterburt** [comment]
really strange, thanks for the comparison @brisvag - here is my environment for comparison

```yaml
napari: 0.4.9
Platform: macOS-11.2.1-x86_64-i386-64bit
System: MacOS 11.2.1
Python: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:15)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.05.0
VisPy: 0.6.6

OpenGL:
  - GL version:  2.1 Metal - 71.0.7
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0

Plugins:
  - console: 0.0.3
  - scikit-image: 0.4.9
  - svg: 0.1.5

```
