### ISSUE TITLE
Warning when starting napari

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3224]
## 🐛 Bug

Hi all, I'm just testing napari 0.4.11rc0. When starting napari, it outputs this every time:

```
Validation errors in config file(s).
The following fields have been reset to the default value:

plugins -> call_order
  none is not an allowed value (type=type_error.none.not_allowed)
```

## To Reproduce

1. start napari from command line

## Expected behavior

The config file is saved correctly when napari closes. Afterwards, this message doesn't show anymore.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.4.11rc0
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.19.5
SciPy: 1.7.1
Dask: 2021.05.1
VisPy: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 466.77
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- Measurements (Plot profile): 0.1.3
- Measurements (skimage regionprops): 0.1.6
- Search (Plugin): 0.1.0
- Segmentation (OCLRFC): 0.4.4
- Segmentation (split/merge): 0.1.2
- Utilities (skimage regionprops): 0.1.6
- Visualization(B/C): 0.1.1
- aicsimageio-in-memory: 0.3.5
- cellpose-napari: 0.1.3
- clEsperanto: 0.10.0
- console: 0.0.3
- napari-yapic-prediction: 0.1.dev99
- ome-types: 0.2.7
- omero: 0.1.1
- scikit-image: 0.4.11rc0
- svg: 0.1.5

 - Any other relevant information:

**Comment by tlambert03** [comment]
the warning itself is not unusual, but the fact that it's not resetting is... I wonder if this is another permissions issue in your environment.  Can you give me the content of your settings.yaml?

**Comment by haesleinhuepf** [comment]
Sure! There you go (I just removed some confidental paths):
```
appearance: {}
application:
  first_time: false
  open_history:
  - C:/this/was/a/confidental/path
  preferences_size:
  - -1
  - -1
  save_history:
  - C:/this/was/a/confidental/path
  - C:\this\was\a\confidental\path
  window_fullscreen: false
  window_maximized: false
  window_position:
  - 432
  - 126
  window_size:
  - 1301
  - 733
  window_state: '!QBYTE_AAAA/wAAAAD9AAAAAwAAAAAAAAECAAACsPwCAAAAAvsAAAAcAGwAYQB5AGUAcgAgAGMAbwBuAHQAcgBvAGwAcwEAAAAXAAABKwAAASsAAAEr+wAAABQAbABhAHkAZQByACAAbABpAHMAdAEAAAFCAAABhQAAALEA////AAAAAQAAAZYAAAKw/AIAAABQ+wAAABoAYQBjAHQAaQB2AGkAdAB5ACAAZABvAGMAawAAAAAAAAAAAQAAADIA////+wAAACQAUwB0AGEAcgBEAGkAcwB0ADoAIABTAHQAYQByAEQAaQBzAHQBAAAAFwAABEQAAAAAAAAAAPsAAAAGAE0AYQBwAAAAArEAAAARAAAAAAAAAAD7AAAAGgBMAGEAYgBlAGwAIABmAGkAbAB0AGUAcgBzAQAAAl8AAACqAAAAAAAAAAD7AAAAMgBuAGEAcABhAHIAaQAtAGYAZQBhAHQAdQByAGUAcwA6ACAAZgBlAGEAdAB1AHIAZQBzAQAAABcAAADOAAAAAAAAAAD7AAAAPgBjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAEIAYQBjAGsAZwByAG8AdQBuAGQAIAByAGUAbQBvAHYAYQBsAQAAABcAAAENAAAAAAAAAAD7AAAAGgBOAG8AaQBzAGUAIAByAGUAbQBvAHYAYQBsAAAAAmMAAACmAAAAAAAAAAD7AAAAJABCAGEAYwBrAGcAcgBvAHUAbgBkACAAcgBlAG0AbwB2AGEAbAAAAAJjAAAADQAAAAAAAAAA+wAAAA4AQwBvAG0AYgBpAG4AZQAAAAKVAAAAdAAAAAAAAAAA+wAAACAATABhAGIAZQBsACAAcAByAG8AYwBlAHMAcwBpAG4AZwAAAAEmAAAACQAAAAAAAAAA+wAAACAATABhAGIAZQBsACAAcAByAG8AYwBlAHMAcwBpAG4AZwAAAAKxAAAADQAAAAAAAAAA+wAAACQATABhAGIAZQBsACAAbQBlAGEAcwB1AHIAZQBtAGUAbgB0AHMAAAACsQAAABEAAAAAAAAAAPsAAAA0AEwAYQBiAGUAbABlAGQAIABpAG0AYQBnAGUAIABtAGUAYQBzAHUAcgBlAG0AZQBuAHQAcwEAAAKVAAAAdAAAAAAAAAAA+wAAADAAYwBsAEUAcwBwAGUAcgBhAG4AdABvADoAIABzAHAAbABpAHQAIABzAHQAYQBjAGsBAAAAFwAAAywAAAAAAAAAAPsAAAA2AGMAbABFAHMAcABlAHIAYQBuAHQAbwA6ACAAcwBlAHQAIAB2AG8AeABlAGwAIABzAGkAegBlAAAAAZ4AAAAJAAAAAAAAAAD7AAAASgBjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAGEAdQB0AG8AIABiAHIAaQBnAGgAdABuAGUAcwBzACAAYwBvAG4AdAByAGEAcwB0AAAAASkAAAAJAAAAAAAAAAD7AAAAKgBNAGUAYQBzAHUAcgBlACAAbABhAGIAZQBsAGUAZAAgAGkAbQBhAGcAZQEAAAIYAAAAjwAAAAAAAAAA+wAAAEoAbgBhAHAAYQByAGkAXwB3AGUAYgBjAGEAbQA6ACAAQwBvAG4AdABpAG4AdQBvAHUAcwAgAEEAYwBxAHUAaQBzAGkAdABpAG8AbgAAAAAXAAAABQAAAAAAAAAA+wAAABAAQgBpAG4AYQByAGkAegBlAAAAAw0AAABYAAAAAAAAAAD7AAAADgBDAG8AbQBiAGkAbgBlAAAAAtkAAACoAAAAAAAAAAD7AAAAEgBUAHIAYQBuAHMAZgBvAHIAbQEAAAFTAAACLgAAAAAAAAAA+wAAAGAAYwBsAEUAcwBwAGUAcgBhAG4AdABvADoAIABhAHUAdABvACAAYgByAGkAZwBoAHQAbgBlAHMAcwAgAGMAbwBuAHQAcgBhAHMAdAAgAGEAbABsACAAaQBtAGEAZwBlAHMBAAABpQAAAdwAAAAAAAAAAPsAAAA0AG4AYQBwAGEAcgBpAC0AZgBlAGEAdAB1AHIAZQBzADoAIABmAGUAYQB0AHUAcgBpAHoAZQEAAAJTAAABrwAAAAAAAAAA+wAAAHIATwBwAGUAbgBDAEwAXwBSAGEAbgBkAG8AbQBfAEYAbwByAGUAcwB0AF8AQwBsAGEAcwBzAGkAZgBpAGUAcgA6ACAAcAByAGUAZABpAGMAdAAgAHAAaQB4AGUAbAAgAGMAbABhAHMAcwBpAGYAaQBlAHIBAAABfwAAAoMAAAAAAAAAAPsAAAAQAEIAaQBuAGEAcgBpAHoAZQAAAAOqAAAAWAAAAAAAAAAA+wAAAG4ATwBwAGUAbgBDAEwAXwBSAGEAbgBkAG8AbQBfAEYAbwByAGUAcwB0AF8AQwBsAGEAcwBzAGkAZgBpAGUAcgA6ACAAdAByAGEAaQBuACAAbABhAGIAZQBsACAAYwBsAGEAcwBzAGkAZgBpAGUAcgEAAAAXAAACNQAAAAAAAAAA+wAAAHIATwBwAGUAbgBDAEwAXwBSAGEAbgBkAG8AbQBfAEYAbwByAGUAcwB0AF8AQwBsAGEAcwBzAGkAZgBpAGUAcgA6ACAAcAByAGUAZABpAGMAdAAgAGwAYQBiAGUAbAAgAGMAbABhAHMAcwBpAGYAaQBlAHIBAAACTgAAAg0AAAAAAAAAAPsAAABIAGMAbABFAHMAcABlAHIAYQBuAHQAbwA6ACAAYwBvAG4AdgBlAHIAdAAgAHQAbwAgADIAZAAgAHQAaQBtAGUAbABhAHAAcwBlAAAAAM4AAAAFAAAAAAAAAAD7AAAATgBuAGEAcABhAHIAaQAtAHMAawBpAG0AYQBnAGUALQByAGUAZwBpAG8AbgBwAHIAbwBwAHMAOgAgAHIAZQBnAGkAbwBuAHAAcgBvAHAAcwEAAAFJAAABDwAAAAAAAAAA+wAAAE4AbgBhAHAAYQByAGkALQBzAGsAaQBtAGEAZwBlAC0AcgBlAGcAaQBvAG4AcAByAG8AcABzADoAIAByAGUAbQBvAHYAZQAgAGEAeABpAHMBAAAAFwAABEEAAAAAAAAAAPsAAAAUAFAAcgBvAGoAZQBjAHQAaQBvAG4AAAAEAwAAAAkAAAAAAAAAAPsAAAAUAFAAcgBvAGoAZQBjAHQAaQBvAG4AAAAEAwAAAA0AAAAAAAAAAPsAAAAUAFAAcgBvAGoAZQBjAHQAaQBvAG4BAAAEAwAAAFgAAAAAAAAAAPsAAABSAGMAbABFAHMAcABlAHIAYQBuAHQAbwA6ACAAcwBlAHQAIAB2AG8AeABlAGwAIABzAGkAegBlACAAbwBmACAAYQBsAGwAIABsAGEAeQBlAHIAcwEAAAAXAAAERAAAAAAAAAAA+wAAAGYAbgBhAHAAYQByAGkALQBzAGsAaQBtAGEAZwBlAC0AcgBlAGcAaQBvAG4AcAByAG8AcABzADoAIABkAHUAcABsAGkAYwBhAHQAZQAgAGMAdQByAHIAZQBuAHQAIABmAHIAYQBtAGUAAAAAFwAAAAUAAAAAAAAAAPsAAABuAE8AcABlAG4AQwBMAF8AUgBhAG4AZABvAG0AXwBGAG8AcgBlAHMAdABfAEMAbABhAHMAcwBpAGYAaQBlAHIAOgAgAHQAcgBhAGkAbgAgAHAAaQB4AGUAbAAgAGMAbABhAHMAcwBpAGYAaQBlAHIAAAAAFwAAAWwAAAAAAAAAAPsAAAB6AE8AcABlAG4AQwBMAF8AUgBhAG4AZABvAG0AXwBGAG8AcgBlAHMAdABfAEMAbABhAHMAcwBpAGYAaQBlAHIAOgAgAGMAbwBuAG4AZQBjAHQAZQBkACAAYwBvAG0AcABvAG4AZQBuAHQAIABsAGEAYgBlAGwAaQBuAGcAAAAAFwAAA0sAAAAAAAAAAPsAAAAyAGMAZQBsAGwAcABvAHMAZQAtAG4AYQBwAGEAcgBpADoAIABjAGUAbABsAHAAbwBzAGUBAAAAvgAAAqcAAAAAAAAAAPsAAABWAG4AYQBwAGEAcgBpAC0AbQBhAG4AdQBhAGwALQBzAHAAbABpAHQALQBhAG4AZAAtAG0AZQByAGcAZQAtAGwAYQBiAGUAbABzADoAIABtAGUAcgBnAGUBAAAAFwAAAMoAAAAAAAAAAPsAAABWAG4AYQBwAGEAcgBpAC0AbQBhAG4AdQBhAGwALQBzAHAAbABpAHQALQBhAG4AZAAtAG0AZQByAGcAZQAtAGwAYQBiAGUAbABzADoAIABzAHAAbABpAHQBAAAA4wAAAWsAAAAAAAAAAPsAAAAsAFMAcABsAGkAdAAgAGEAbgBkACAAbQBlAHIAZwBlADoAIABtAGUAcgBnAGUBAAAAFwAAAMoAAAAAAAAAAPsAAAAsAFMAcABsAGkAdAAgAGEAbgBkACAAbQBlAHIAZwBlADoAIABzAHAAbABpAHQBAAAA4wAAAWsAAAAAAAAAAPsAAABEAEEAcwBzAGkAcwB0AGEAbgB0ACAAKABjAGwARQBzAHAAZQByAGEAbgB0AG8AKQA6ACAAQQBzAHMAaQBzAHQAYQBuAHQAAAAAFwAAAjcAAAAAAAAAAPsAAAAIAE0AZQBzAGgBAAAEAAAAAFgAAAAAAAAAAPsAAAAwADkAIABjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAEEAcwBzAGkAcwB0AGEAbgB0AQAAABcAAAJ4AAAAAAAAAAD7AAAAaABTAGUAZwBtAGUAbgB0AGEAdABpAG8AbgAgACgATwBDAEwAUgBGAEMAKQA6ACAAVAByAGEAaQBuACAATwBDAEwAUgBGAEMAIABwAGkAeABlAGwAIABjAGwAYQBzAHMAaQBmAGkAZQByAQAAABcAAARBAAAAAAAAAAD7AAAAbABWAGkAcwB1AGEAbABpAHoAYQB0AGkAbwBuADoAIABCAHIAaQBnAGgAdABuAGUAcwBzACAALwAgAEMAbwBuAHQAcgBhAHMAdAA6ACAARQB4AGEAbQBwAGwAZQAgAFEAIABXAGkAZABnAGUAdAEAAAAXAAACiQAAAAAAAAAA+wAAAHQAVgBpAHMAdQBhAGwAaQB6AGEAdABpAG8AbgA6ACAAQgByAGkAZwBoAHQAbgBlAHMAcwAgAC8AIABDAG8AbgB0AHIAYQBzAHQAOgAgAEIAcgBpAGcAaAB0AG4AZQBzAHMAXwAgAEMAbwBuAHQAcgBhAHMAdAEAAAAXAAACiQAAAAAAAAAA/AAAABcAAAJOAAAAAAD////6AAAAAAEAAAAB+wAAAEgAVgBpAHMAdQBhAGwAaQB6AGEAdABpAG8AbgBfADoAIABCAHIAaQBnAGgAdABuAGUAcwBzAF8AIABDAG8AbgB0AHIAYQBzAHQBAAAAAP////8AAAAAAAAAAPsAAAAMAEYAaQBsAHQAZQByAQAAAmcAAACkAAAAAAAAAAD7AAAADABGAGkAbAB0AGUAcgEAAAMIAAAAfQAAAAAAAAAA+wAAADwAYwBsAEUAcwBwAGUAcgBhAG4AdABvADoAIABSAGUAbQBvAHYAZQAgAGIAYQBjAGsAZwByAG8AdQBuAGQBAAABogAAALMAAAAAAAAAAPsAAABOAFYAaQBzAHUAYQBsAGkAegBhAHQAaQBvAG4AKABCAC8AQwApADoAIABCAHIAaQBnAGgAdABuAGUAcwBzACAAQwBvAG4AdAByAGEAcwB0AQAAABcAAAGtAAAAAAAAAAD7AAAADABGAGkAbAB0AGUAcgEAAAMdAAAAfQAAAAAAAAAA+wAAABwATQBlAGEAcwB1AHIAZQAgAGwAYQBiAGUAbABzAAAAAuUAAABYAAAAAAAAAAD7AAAALABMAGEAYgBlAGwAIABuAGUAaQBnAGgAYgBvAHIAIABmAGkAbAB0AGUAcgBzAAAAApUAAACoAAAAAAAAAAD7AAAAaABTAGUAZwBtAGUAbgB0AGEAdABpAG8AbgAgACgATwBDAEwAUgBGAEMAKQA6ACAAVAByAGEAaQBuACAATwBDAEwAUgBGAEMAIABsAGEAYgBlAGwAIABjAGwAYQBzAHMAaQBmAGkAZQByAQAAABcAAAI1AAAAAAAAAAD7AAAASABjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAGMAbwBuAHYAZQByAHQAIABsAGEAYgBlAGwAcwAgAHQAbwAgAGkAbQBhAGcAZQEAAAJOAAAA7wAAAAAAAAAA+wAAABwAUAByAG8AYwBlAHMAcwAgAGwAYQBiAGUAbABzAQAAAbsAAAGCAAAAAAAAAAD7AAAASABjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAGMAbwBuAHYAZQByAHQAIABpAG0AYQBnAGUAIAB0AG8AIABsAGEAYgBlAGwAcwEAAAAXAAAAlQAAAAAAAAAA+wAAABwAUAByAG8AYwBlAHMAcwAgAGwAYQBiAGUAbABzAQAAAbsAAAGCAAAAAAAAAAD7AAAAGgBSAGUAbQBvAHYAYQBsACAAbgBvAGkAcwBlAAAAAekAAAAJAAAAAAAAAAD7AAAAGgBSAGUAbQBvAHYAYQBsACAAbgBvAGkAcwBlAAAAAekAAAANAAAAAAAAAAD7AAAAQgBjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAG0AYQBrAGUAIABsAGEAYgBlAGwAcwAgAGUAZABpAHQAYQBiAGwAZQEAAAGHAAABCAAAAAAAAAAA+wAAACIAUgBlAG0AbwB2AGUAIABiAGEAYwBrAGcAcgBvAHUAbgBkAAAAAekAAAAJAAAAAAAAAAD7AAAACgBMAGEAYgBlAGwBAAACAwAAAIwAAAAAAAAAAPsAAAAsAGMAbABFAHMAcABlAHIAYQBuAHQAbwA6ACAAQQBzAHMAaQBzAHQAYQBuAHQBAAAAFwAAAeoAAAAAAAAAAPsAAAAiAFIAZQBtAG8AdgBlACAAYgBhAGMAawBnAHIAbwB1AG4AZAAAAAHpAAAACQAAAAAAAAAA+wAAAAoATABhAGIAZQBsAQAAAgMAAACMAAAAAAAAAAD7AAAAJgBjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAEYAaQBsAHQAZQByAAAAASwAAAFjAAAAAAAAAAD7AAAARgBuAGEAcABhAHIAaQAtAHAAbAB1AGcAaQBuAC0AcwBlAGEAcgBjAGgAOgAgAFAAbAB1AGcAaQBuACAAUwBlAGEAcgBjAGgBAAAAFwAAAlUAAAAAAAAAAPsAAAA2AGMAbABFAHMAcABlAHIAYQBuAHQAbwA6ACAATQBlAGEAcwB1AHIAZQAgAGwAYQBiAGUAbABzAAAAAL4AAAGuAAAAAAAAAAD7AAAAGgBEAG8AYwBrACAAdwBpAGQAZwBlAHQAIAAxAQAAAO4AAAF+AAAAAAAAAAD7AAAAUgBjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAHMAdABhAHQAaQBzAHQAaQBjAHMAIABvAGYAIABsAGEAYgBlAGwAZQBkACAAcABpAHgAZQBsAHMAAAAA/wAAAW0AAAAAAAAAAPsAAABuAE0AZQBhAHMAdQByAGUAbQBlAG4AdABzACAAKABzAGsAaQBtAGEAZwBlACAAcgBlAGcAaQBvAG4AcAByAG8AcABzACkAOgAgAHMAawBpAG0AYQBnAGUAIAByAGUAZwBpAG8AbgBwAHIAbwBwAHMAAAABoQAAAV8AAAAAAAAAAPsAAAA8AFMAZQBhAHIAYwBoACAAKABQAGwAdQBnAGkAbgApADoAIABQAGwAdQBnAGkAbgAgAFMAZQBhAHIAYwBoAQAAABcAAAIzAAAAAAAAAAD7AAAAMgBjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAFIAZQBtAG8AdgBlACAAbgBvAGkAcwBlAAAAAOEAAAAJAAAAAAAAAAD7AAAAJABjAGwARQBzAHAAZQByAGEAbgB0AG8AOgAgAEwAYQBiAGUAbAAAAAC6AAABkAAAAAAAAAAA+wAAADoAYwBsAEUAcwBwAGUAcgBhAG4AdABvADoAIABjAG8AbgB2AGUAcgB0ACAAdABvACAAbgB1AG0AcAB5AAAAABcAAABXAAAAAAAAAAD7AAAAUgBNAGUAYQBzAHUAcgBlAG0AZQBuAHQAcwAgACgAUABsAG8AdAAgAHAAcgBvAGYAaQBsAGUAKQA6ACAAUABsAG8AdAAgAFAAcgBvAGYAaQBsAGUBAAAAFwAAArAAAAAAAAAAAAAAAAMAAAYrAAABQfwBAAAAAfsAAAAOAGMAbwBuAHMAbwBsAGUAAAAAAAAABisAAAAyAP///wAABBEAAAKwAAAABAAAAAQAAAAIAAAACPwAAAAA'
experimental: {}
plugins:
  call_order: null
  disabled_plugins:
  - aicsimageio-out-of-memory
  - napari-features
shortcuts: {}
```

According to the time stamp the file was saved all the time.
![image](https://user-images.githubusercontent.com/12660498/130482185-442b1e33-32f0-43d7-a432-8b79e37fcef9.png)
