### ISSUE TITLE
Volume attenuation test failure on updating vendored vispy code

### ISSUE THREAD

**Issue by brisvag** [napari/napari#3301]
## 🐛 Bug

As noted in [this comment](https://github.com/napari/napari/pull/3252#discussion_r698532395), updating the code to upstream vispy (a change that looks trivially correct) causes a test failure. I'm not sure how to solve this, and it was keeping up a mostly unrelated PR, so I decided to revert it and open this issue. Check the original comment for some additional context.

## To Reproduce

With this change to `VolumeVisual`, run `NAPARI_POPUP_TESTS=1 pytest -k 'test_with_screenshot and attenuation'`.

```diff
     @attenuation.setter
     def attenuation(self, value):
         self._attenuation = float(value)
+        if 'u_attenuation' in self.shared_program:
+            self.shared_program['u_attenuation'] = self._attenuation
-        self.shared_program['u_attenuation'] = self._attenuation
         self.update()

```

Error:
```python
    @skip_on_win_ci
    @skip_local_popups
    def test_changing_image_attenuation(make_napari_viewer):
        """Test changing attenuation value changes rendering."""
        data = np.zeros((100, 10, 10))
        data[-1] = 1

        viewer = make_napari_viewer(show=True)
        viewer.dims.ndisplay = 3
        viewer.add_image(data, contrast_limits=[0, 1])
        viewer.layers[0].rendering = 'attenuated_mip'

        viewer.layers[0].attenuation = 0.5
        screenshot = viewer.screenshot(canvas_only=True, flash=False)
        center = tuple(np.round(np.divide(screenshot.shape[:2], 2)).astype(int))
        # Check that rendering has not been attenuated
>       assert screenshot[center + (0,)] > 80
E       assert 50 > 80

napari/_tests/test_with_screenshot.py:335: AssertionError
```

## Expected behavior

Unsure whether the test is wrong, or something breaks it with this change.

## Environment

```yaml
napari: 0.4.11.dev111+gaa815ea0
Platform: Linux-5.13.13-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2020.12.0
VisPy: 0.7.3

OpenGL:
- GL version: 4.6.0 NVIDIA 470.63.01
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-oriented-points-picker: 0.1.dev1+g7336e66.d20210713
- napari-properties-plotter: 0.2.0
- ndtiffs: 0.1.1
- scikit-image: 0.4.9
- svg: 0.1.5
```

## Additional context

https://github.com/napari/napari/pull/3252#discussion_r698532395
