### ISSUE TITLE
npe2 dock widget TypeError

### ISSUE THREAD

**Issue by nclack** [napari/napari#3617]
## 🐛 Bug

Binding a `napari_experimental_provide_dock_widget()` function as the callable for a npe2 widget raises a TypeError when the corresponding menu item is invoked.  

This is because some plugins return a `(callable,dict)` and other just the `callable`.

## To reproduce

1. Install the branch corresponding to  [tlambert03/npe2#26]
2. Adapt `napari-animation` to be a npe2 plugin. (e.g see [this branch](https://github.com/nclack/napari-animation/tree/npe2))
3. attempt to start the animation wizard from the plugins menu
 
Example napari.yaml (this format may change)
```yaml
name: napari_animation
display_name: animation
license: BSD-3-Clause
entry_point: napari_animation
contributions:
  commands:
    - id: napari_animation.widget
      python_name: napari_animation._hookimpls:napari_experimental_provide_dock_widget
      title: napari animation widget
  widgets:
    - command: napari_animation.widget
      name: wizard
```

Example entry points section in setup.cfg:
```ini
[options.entry_points]
# napari.plugin = 
	# animation = napari_animation
napari.manifest = 
    napari-animation = napari_animation:napari.yaml
```

## Traceback

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/src/CZI/napari/napari/_qt/menus/plugins_menu.py in _add_toggle_widget(key=('napari_animation', 'Wizard'), hook_type='dock')
    107 
    108                 if hook_type == 'dock':
--> 109                     self._win.add_plugin_dock_widget(*key)
        global self._win.add_plugin_dock_widget = undefined
        key = ('napari_animation', 'Wizard')
    110                 else:
    111                     self._win._add_plugin_function_widget(*key)

~/src/CZI/napari/napari/_qt/qt_main_window.py in add_plugin_dock_widget(self=<napari._qt.qt_main_window.Window object>, plugin_name='napari_animation', widget_name='Wizard')
    687 
    688         # instantiate the widget
--> 689         wdg = Widget(**kwargs)
        wdg = undefined
        Widget = (<class 'napari_animation._qt.animation_widget.AnimationWidget'>, {'name': 'Wizard', 'add_vertical_stretch': False})
        kwargs = {}
    690 
    691         # Add dock widget

TypeError: 'tuple' object is not callable
```
