### ISSUE TITLE
Docked widgets are resizeable outside of their enclosure

### ISSUE THREAD

**Issue by brisvag** [napari/napari#3624]
## 🐛 Bug

While checking out how to address #3620, I found out this:

https://user-images.githubusercontent.com/23482191/141996124-b45e4cbf-052d-479d-8943-ea3c0bfc984f.mp4

## To Reproduce

Click and drag just a tiny bit to the right of the resizing handle of the right side area.

## Environment

```yaml
napari: 0.4.12rc1.dev12+g99e61c4e
Platform: Linux-5.14.15-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.10.0
VisPy: 0.9.1

OpenGL:
- GL version: 4.6.0 NVIDIA 495.44
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-molecule-reader: 0.1.dev2+g06b598e.d20210914
- napari-properties-plotter: 0.2.0
- ndtiffs: 0.1.1
- ome-types: 0.2.9
- scikit-image: 0.4.9
- svg: 0.1.5
```
