### ISSUE TITLE
Public access to Window.qt_viewer.layer_to_visual

### ISSUE THREAD

**Issue by LREIN663** [napari/napari#4121]
## 🚀 Feature
I would like to have public access to Window.qt_viewer.layer_to_visual

## Motivation
napari particles (https://github.com/maweigert/napari-particles), which I want to incorporate into a napari dock widget, uses 

`viewer.window.qt_viewer.layer_to_visual[self].node`
as well as 
`self._viewer.window.qt_viewer.controls.widgets[self]`. 
While I found the second one not being necesary for my purpose the first one seems to be.

**Comment by tlambert03** [comment]
ah, yeah you're with @superchromix correct?  This is going to be an interesting/challenging case.   We don't have a specification for creating a fully custom layer type as a plugin, so this is absolutely pushing the boundaries of what the plugin system is currently supposed to do.  Those are two rather core objects to expose there (doing so would be somewhat akin to just going back to allowing private access).  If any plugin can modify the vispy visual and layer controls, how does any other plugin (or the user) have any guarantee about the "state" that they might find those controls or visual nodes in?

@maweigert and I discussed this a while back as well and anticipated the difficulty of a custom layer type as a plugin, it would be fantastic if this particles layer could be added to core napari, since it as far as the underlying data model goes, it's rather similar to points right?  (though I recognize that functionally it's actually a subclass of `Surface`).  

In any case, all that said, this is clearly **awesome** functionality that we have to make accessible one way or the other.
if we don't want to try to get this into core, we need to have a more general conversation about how a custom layer should be added via plugins.  As a very rough stab for a custom layer type spec, one could imagine:

```yaml
contributions:
   - layers:
      - name: Particles
        model: napari_particles.particles:Particles
        controls: napari_particles._qt:ParticlesControl
        visual: napari_partiles._vispy:ParticlesVisual
```

where `model` is a subclass of `napari.layers.Layer`, `controls` is a subclass of `_qt.layer_controls.qt_layer_controls_base.QtLayerControls` and `visual` is a subclass of `_vispy.layers.base.VispyBaseLayer`.

what do @sofroniewn & @jni think? (and also @maweigert... your thoughts on how you as a developer would have this "ideally" integrated are greatly appreciated, while also keeping your dev hat on asking "should any plugin be able to do this" :smile:)

**Comment by sofroniewn** [comment]
My preference is that we try and get these custom layers contributed to the core so that so that vispy and qt don't get passed through the plugin interface, and we allow all plugin developers to use them in their own plugins. I already know a couple different folks who would want to use a Particles layer.

I've also always wanted our coupling to vispy to be loose so that we could move away from it one day and our plugins would keep working. Allowing `visual` above would make that much harder, but maybe it's ok.

Similarly I'd like our coupling to Qt to be loose too. For layer controls in general I've been hoping we'd move to a schema/ pydantic model that could autogenerate into a widget too (or maybe just decorators on `Layer` that mean we don't need anything extra). I'd prefer not to open up the controls widget here but to work on that autogeneration.

If we could get to

```
contributions:
   - layers:
      - name: Particles
        model: napari_particles.particles:Particles
        visual: napari_partiles._vispy:ParticlesVisual
```

That would already be better IMHO, but I'm looking forward to what others have to say.
