### ISSUE TITLE
Add proxy/ssl configuration and unify code making url requests

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#4397]
## 🚀 Feature

Currently we have some code that pings the web for information, the plugin dialog, the updates dialog, and others may come in the future. It would be nice to unify these calls under some "download manager" so we can define any additional configuration (proxy settings / ssl verficiation) in a single place.

## Motivation

Conda configuration exposes something like:

```yaml
proxy_servers:
  http: http://corp.com:8080
  https: https://corp.com:8080

ssl_verify: False
```

https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-winxp-with-proxy.html

Now that the bundle is up and depending on conda, it would be great to make sure we can use these settings and have all code paths pinging the web also use them.
