### ISSUE TITLE
NAP-6 Implementation Plan

### ISSUE THREAD

**Issue by DragaDoncila** [Napari/napari#7012]
## 🧰 Task
This issue is here to track current state of implementation w.r.t NAP-6. 

### Other Related Considerations
- [x] npe2 PR adding a mapping from command IDs to associated menu items for each plugin
    - just needs review I think?
    - useful because we need both the command object and the menu contrib object without iterating
- [x] PR adding empty placeholders to menus
    - If you look at #7011 you'll notice the empty submenus are not great as a UI experience. #6950 was the first attempt to address this issue, but it was ultimately implemented in #7038
    - [ ] The code needs testing and the keys should be moved off the layerlist context
- [ ] On contexts, keys, and context hierarchies

### Core NAP-6

- [x] Add `Layers -> Layer Type` and `Layers -> Data` submenus for conversions
    - not only can we populate with our own stuff, but @jni and I found stuff that could go in there from Tools menu
    - [x] update NAP
- [x] bring out stuff from `Layers -> Edit` into top `Layers`
    - Peter, Juan and I spoke about this at North America meeting and we felt that having top `Edit` and  `Layers -> Edit` is weird, but if we just move them out we can avoid this issue.
    - [x] NAP
- [x] top level Layers not contributable
    - [x] NAP
    - [x] maybe need to update the bit about submenu
- [x] name of plugin should be shown in menu next to action name
    - [x] pure commands need plugin name

This MVP version of NAP-6 will be released in v0.5.0.

- [ ] Add top level edit menu
    - [ ] update NAP
- [ ] Distribute layer context actions among Edit and Layers menus
    - [ ] update NAP
- [ ] Add top-level Develop menu (replaces Debug menu)
	- [ ] Activated by a preference
	- [ ] update NAP 
- [ ] Order & grouping of items
    - [ ] napari always on top
    - [ ] plugin declared group and order respected 
- [ ]  Decide exactly what types may be used as type hints for dependency injection in a plugin command function (these are the names declared in the `app.injection_store.namespace`), and ensure we have providers for these types. Also document this.
    - [ ] We are in rough agreement that "pure" commands in the `Layers` menu should work on the selected layer (if they take a layer at all). This should be documented and made explicit in the code.
- [ ] Decide on which context keys we want to make available to plugin developers for use in `when` and `enablement` expressions, where we expose them, and how developers can add more.
    - [ ] Implement parsing and respecting `when` expressions for menu items
    - [ ] Implement parsing and respecting `enablement` expressions for commands
- [ ] Allow plugins to declare arbitrary submenus under their own plugin’s `self` menu
    - [ ] NAP update from plugin name to `self`
- [ ] Add icon/something to signal when a menu item is a widget, so users will know when clicking on something will open a widget vs run something (we can and potentially should ensure adherence on the napari side)
- [ ] Adding name of plugin to menu item titles
    - [ ] @jni thinks we should be stripping `napari` from the plugin name (even the display name??) but I have concerns about mangling plugin names 
    - [ ] currently the name of the plugin also appears when the action is shown in the `Plugins` menu, even though all actions are grouped under a submenu of the same name. This is visually quite annoying, so we should look at whether we can strip the plugin name in this case. Note that a single action can't have different titles depending on the menu it's part of, so we need to either implement this, or change the name of the qt object directly.
- [ ] A key goal for our menu contributions is that users are never surprised by the outcome of clicking on an action. Since actions can come from all sorts of sources and **may** have destructive effects, we want to provide as much information as possible to users about each menu item
    - [ ] Add `description` field to manifest - make it required??
        - [ ] does it live on the `command` or on the `MenuContribution`? 
    - [ ] Read `description` into `status tip` field of `Action`
        - [ ] is that a super weird place to put it? Will users ever look there? 
- [ ] Rather than using the full menu path for contributable menus, plugin developers should be able to specify a unique key, and we complete the full menu path for them
    - [ ] Decide on the unique keys
    - [ ] Implement unravelling
    - [ ] Backwards compatibility? 
    - [ ] NAP
- [ ] Icons
    - [ ] Look at whether icons are an option for disambiguating menu item source (rather than full name) 
    - [ ] Figure out how to use superqt.fonticons and whether this should be exposed to plugin devs
    - [ ] Do they work in menu bars?
    - [ ] Add docs and potential examples to plugin template
- [ ] sort plugins menu alphabetically (lifted from #6410 as we should be doing this anyway really) 
- [ ] test coverage

### Next Gen Manifest
- [ ] Decide on schema for next gen manifest
    - [ ] Address concerns in #6227
- [ ] Formalize which `Action` fields are exposed to users via the manifest, and which contributions they are exposed in. Related issue #6224
- [ ] Update iterator APIs to match the new manifest structure and how we iterate in `napari` when registering actions
    - [ ] Related issue #6326  

### Doc Updates

- [ ] everything from implementation plan
- [ ] pure commands in Layers should act on selected layer
- [ ] more detail on each discussion/decision in bottom summary
- [ ] …s for widgets not …s for commands
- [x]  open issue add todo list point from nap
- [ ] context menu?
	- now that we've removed it from contributables, need to maybe update first example or say something about removal
- [ ] add usage documentation
- [ ] document exported context keys
- [ ] expose MenuContribution guide in npe2
- [ ] add menu contributions to napari-plugin-template

**Comment by lucyleeow** [comment]
So I made  #6174 a while ago but I am happy to close. Feel free to migrate any items from that issue.

**Comment by DragaDoncila** [comment]
Totally forgot about that issue... will need to transfer some stuff over

**Comment by lucyleeow** [comment]
I think manifest v2 would probably address https://github.com/napari/napari/issues/6227 (at least further manifest problems can be in a new issue)

**Comment by adamltyson** [comment]
We (@brainglobe) are very interested in plugin submenus. I have a couple of questions about the future implementation of this that weren't clear to me from NAP-6:
1. Will it be possible to have an arbitrary number of submenu levels (within reason!)?
2. Will it be possible for plugins from >1 package to go under the same menu? Currently BrainGlobe has 8 plugins that have between 1-3 widget contributions. We would ideally like to structure these something like this:

```
Plugins
└── brainglobe
    ├── brainglobe-registration*
    ├── brainglobe-segmentation*
    ├── brainglobe-stitch*
    ├── brainmapper*
    ├── brainreg*
    ├── brainrender*
    │   ├── brainrender
    │   └── manage-atlases
    └── cellfinder*
        ├── curate
        ├── detect
        └── train
```

Currently everything with a `*` is a separate plugin and PyPI package. We could achieve what we need by removing the contributions from each package and creating a "metaplugin" that defined the contributions for every plugin. We'd rather not do this because it would lead to some users needing to install a few GB of dependencies for a basic task. Ideally as each plugin was installed, it would just end up under the `brainglobe` submenu.

TL;DR - can multiple plugins share the same plugin submenu?

**Comment by DragaDoncila** [comment]
@adamltyson thanks for your comment - great to hear you're wanting to use the plugin submenus! Apologies for some of the details missing from the NAP-6 doc. They're not in there because we're not sure on the exact implementation yet heh 😅 

> Will it be possible to have an arbitrary number of submenu levels (within reason!)?

Yep, that's the goal. The rough idea is that in your manifest you would have something like this (for this example, assume all your commands are in one plugin):

```yaml
name: brainglobe-napari
display_name: Brainglobe

contributions:
  commands:
    # if this command is just under `Plugins -> Brainglobe` you could just not declare a menu item for it
    # but then you wouldn't be able to group or order it, it would just show up at the bottom of whatever commands you 
    # did declare menu items for
    - id: brainglobe-napari.register
      title: Register
      python_name: brainglobe_napari:register
    - id: brainglobe-napari.brainrender
      title: Brainrender from Submenu
      python_name: brainglobe_napari:brainrender

  menus:
    self:
      - submenu: self/brainrender
      - command: brainglobe-napari.register
         # would put this command at the top - not currently respected
         group: 0
    self/brainrender:
      - command: brainglobe-napari.brainrender
      - submenu: self/brainrender/deeper
    self/brainrender/deeper:
      - command: ...

  submenus:
    - id: self/brainrender
      label: brainrender
    - id: self/brainrender/deeper
      label: deeper submenu
```

Note that this is just the idea at the moment, and we'd appreciate all your feedback on whether this seems like what you'd want, or if the implementation is a little wonky. We're also looking at rearranging the manifest schema to reduce repetition, but that's a separate story.

> Will it be possible for plugins from >1 package to go under the same menu?

This is not currently in the implementation plan, but we have discussed before. 

For submenus **outside** the plugin's own menu (`self` menu), this is currently possible simply through shared submenu IDs. We haven't yet extended this to the `self` menu because we wouldn't want plugins to "hijack" other plugins' menus without consent 😆 . 

However, we were considering the idea of allowing a plugin to explicitly declare its own `self/*` submenus as "contributable", to enable exactly the kind of ecosystem you're referring to. In that world, you would edit your `brainglobe-napari` manifest to declare the `brainrender` menu as contributable e.g.

```yaml
name: brainglobe-napari
display_name: Brainglobe
...
submenus:
    - id: self/brainrender
      label: brainrender
      contributable: True
```

and then in your `napari-brainrender` plugin manifest you would have something like...

```yaml
name: napari-brainrender
display_name: Brainrender
menus:
  ...
  # use full plugin name of the plugin that declared this menu contributable
  brainglobe-napari/brainrender:
    - command: napari-brainrender.brainrender
```

How does that sound as a proposal? Feel free to tear it apart if you don't like it, the more we hear from you the more useful we can make this!

PS - brainrender is not an easy word to type 😆

**Comment by adamltyson** [comment]
Thanks for your reply @DragaDoncila. I think the hierarchy of submenus is exactly what we need.

Re "sharing" a submenu across plugins. This would be very valuable for us. We have a growing number of interoperable plugins, including some built by others (but built on top of BrainGlobe). It would be great be able to declare the `BrainGlobe` label as contributable, and ideally submenus too. 

My only question is whether the contributable menu could only be defined by one plugin? Ideally this could be defined by all plugins, and then any that were installed ended up in the same menu. 

> we wouldn't want plugins to "hijack" other plugins' menus without consent 

Personally I'm not so bothered about this. One of the side effects of open source, is that people may do things you don't love. It also wouldn't be too onerous to contact plugin devs if we thought that they were using a plugin menu in a manner confusing to users. If anybody did it maliciously, then the plugin could be blocked from the plugin manager.  Anyway, there's nothing to stop someone releasing a plugin called `napari-this-is-better-than-brainglobe-honest` anyway!

**Comment by DragaDoncila** [comment]
@adamltyson my apologies for the delay in getting back to you on this one!

> My only question is whether the contributable menu could only be defined by one plugin? Ideally this could be defined by all plugins, and then any that were installed ended up in the same menu.

Right now, this is how it works for external menus. So, using again the examples of `napari-brainrender` and `brainglobe-napari`, and assuming they both want to share a submenu labelled `Brainglobe Filters` under `Layers -> Filter`, you can achieve this with the following two manifests:

```yaml
name: brainglobe-napari
display_name: Brainglobe

contributions:
  ...
  menus:
    napari/layers/filter:
      - submenu: brainglobe_filters
    brainglobe_filters:
      - command: brainglobe_napari.some_filter
  # this plugin declares the ID and where it's placed
  submenus:
    - id: brainglobe_filters
      label: Brainglobe Filters
```

```yaml
name: napari-brainrender
display_name: Brainrender

contributions:
  ...
  menus:
    # this plugin just refers to the submenu by ID
    brainglobe_filters:
      - command: napari-brainrender.specific_filter
      ...
```

In the scenario above, one plugin declares the submenu and the other just uses it. But you could also declare the submenu in both manifests, and as long as the ID is the same and they're placed in the same `napari` menu, they'll behave as a single menu so the following manifests will achieve the same result as above.

```yaml
name: brainglobe-napari
display_name: Brainglobe

contributions:
  ...
  menus:
    napari/layers/filter:
      - submenu: brainglobe_filters
    brainglobe_filters:
      - command: brainglobe_napari.some_filter
  submenus:
    - id: brainglobe_filters
      label: Brainglobe Filters
```

```yaml
name: napari-brainrender
display_name: Brainrender

contributions:
  ...
  menus:
    # note the duplicate definition
    napari/layers/filter:
      - submenu: brainglobe_filters
    brainglobe_filters:
      - command: napari-brainrender.specific_filter
  # note the duplicate definition
  submenus:
    - id: brainglobe_filters
      label: Brainglobe Filters
```

If I'm understanding correctly, this second option is what you would like implemented? That is, both `brainglobe-napari` and `napari-brainrender` declare some submenu `brainglobe_filters` and this shows up under `Plugins -> Brainglobe Filters` rather than `Plugins -> Brainglobe -> Brainglobe Filters` and `Plugins -> Brainrender -> Brainglobe Filters` respectively? 

The `self` syntax I proposed above would result in the latter if **both** plugins declared a `self/brainglobe_filters` submenu. We hadn't yet considered/discussed opening the top-level `Plugins` menu itself for contribution, but I don't have any immediate objections to it! Curious what others think? @psobolewskiPhD? @jni?

If we were to open up the `Plugins` menu for contribution, then the example above with the `napari/layers/filter` menu would justwork™️  with `napari/plugins`. Then, we could possibly do away with the `self` syntax entirely, and plugins could just use `napari/plugins/plugin-name` when they wanted a submenu under their home menu at `Plugins -> Plugin Name`. They could still choose to declare any submenu under `Plugins -> Plugin Name` as contributable, but by default it wouldn't be.

How does all of that sound?

---

Couple of notes (both for myself and for whomever is following along) about what currently happens with submenu ID conflicts:

- if two plugins declare the same ID in the same location **with different labels**, the first plugin registered wins the label. Everything else works "as expected". We maybe should warn in this case?
- if two plugins declare the same ID **in different locations**, both menus get registered, and all commands registered under that ID (regardless of which plugin declared it) get placed in both menus. I'm not sure what we want to do about this 😬 Maybe just a warning is enough? Maybe it's not a big deal if we provide guidance about choosing IDs e.g. "start the ID with your plugin name if you don't want to risk a clash with communal IDs"?

Also cc'ing @isabela-pf on this one as it's relevant to our discussion from earlier today.
